updates

diff --git a/local/.local/bin/walldl b/local/.local/bin/walldl
--- a/local/.local/bin/walldl
+++ b/local/.local/bin/walldl
@@ -19,17 +19,17 @@ total=$(jq -r '.meta.total' "$tmpfile")
 count=$(gum input --placeholder "Count of images, max is $total:")
 
 if ! [[ $count =~ ^[0-9]+$ ]]; then
-	echo "error: Count not a number" >&2
-	exit 1
+  echo "error: Count not a number" >&2
+  exit 1
 fi
 
 if [[ $count -eq 0 ]]; then
-	exit 0
+  exit 0
 fi
 
 if [[ $count -gt $total ]]; then
-	echo "Max is $total" >&2
-	exit 1
+  echo "Max is $total" >&2
+  exit 1
 fi
 
 pages=$((count / 24))
@@ -37,19 +37,19 @@ pages=$((count / 24))
 paths=$(jq -r '.data[].path' "$tmpfile")
 
 download_and_convert_images() {
-	index=1
-	for path in $(echo "$paths" | uniq | head -n "$count"); do
-		echo "#$index wallpaper:"
-		filepath="$download_dir/$(basename "$path")"
-		wget -P "$download_dir" "$path" -q --show-progress
-		dipc "$theme" -s warm "$filepath" -d "$output_dir"
-		((index = index + 1))
-	done
+  index=1
+  for path in $(echo "$paths" | uniq | head -n "$count"); do
+    echo "#$index wallpaper:"
+    filepath="$download_dir/$(basename "$path")"
+    wget -P "$download_dir" "$path" -q --show-progress
+    # dipc "$theme" -s warm "$filepath" -d "$output_dir"
+    ((index = index + 1))
+  done
 }
 
 get_paths() {
-	page_paths=$(curl -s "https://wallhaven.cc/api/v1/search?sorting=toplist&topRange=$range&ratios=16x9,16x10&page=$1" | jq -r '.data[].path')
-	paths+=$(echo -e "\n$page_paths")
+  page_paths=$(curl -s "https://wallhaven.cc/api/v1/search?sorting=toplist&topRange=$range&ratios=16x9,16x10&page=$1" | jq -r '.data[].path')
+  paths+=$(echo -e "\n$page_paths")
 }
 
 echo "Download $count wallpapers for $range..."
@@ -59,13 +59,13 @@ paths_count=$(echo "$paths" | wc -l)
 page=2 # page to start download with
 
 while [[ $page -le $pages ]]; do
-	get_paths $page
-	((page = page + 1))
+  get_paths $page
+  ((page = page + 1))
 done
 
 if [[ $paths_count -lt $count ]]; then # ensure if there enough images
-	((page = page + 1))
-	get_paths $page
+  ((page = page + 1))
+  get_paths $page
 fi
 
 download_and_convert_images && notify-send -t 1500 -r 470 "$count images were downloaded"
